# ============================================================================ #
#                            D o c k e r   B u i l d
# ============================================================================ #

# Docker Build, Tag & Push to one or more repos
#
# Supports:
#
#   - DockerHub
#   - GHCR - GitHub Container Registry

---
name: Docker Build Push

on:  # yamllint disable-line rule:truthy
  workflow_call:
    inputs:
      repo_tags:
        description: >2
          Full repository:tag list to push to, space or line separated
          eg. username/repo:<tag> (defaults to DockerHub),
          ghcr.io/$GITHUB_REPOSITORY_OWNER/$IMAGE:latest.
        type: string
        required: true
      context:
        description: The Docker context directory for the docker build.
        type: string
        default: .
        required: false
      build-args:
        description: List of build-time variables.
        type: string
        default: ""
        required: false
    secrets:
      DOCKERHUB_USER:
        required: false
      DOCKERHUB_TOKEN:
        required: false

permissions:
  contents: read
  packages: write

defaults:
  run:
    shell: bash -euxo pipefail {0}

env:
  REPO_TAGS: ${{ inputs.repo_tags }}
  DOCKERHUB_USER: ${{ secrets.DOCKERHUB_USER }}
  DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}

jobs:
  # Workaround for GitHub Actions not supporting secrets in step conditionals:
  #
  #   https://github.com/github-community/community/discussions/17983
  #
  #   https://github.com/actions/runner/issues/520
  #
  determine_registries:
    name: Determine Registries
    runs-on: ubuntu-latest
    outputs:
      dockerhub: ${{ steps.setvar.outputs.dockerhub }}
      ghcr: ${{ steps.setvar.outputs.ghcr }}
    steps:
      - name: Set output variables
        id: setvar
        run: |
          if [ -n "$DOCKERHUB_USER" ] &&
             [ -n "$DOCKERHUB_TOKEN" ]; then

            echo "DockerHub registry credentials set"
            echo "dockerhub=true" >> "$GITHUB_OUTPUT"
          fi

  docker_build_push:
    name: Docker Build
    needs: determine_registries
    runs-on: ubuntu-latest
    steps:
      - name: Environment
        run: env | sort

      - uses: actions/checkout@v4.2.2

      - name: Docker Login GHCR
        env:
          TOKEN: ${{github.token}}
        run: |2
          docker login ghcr.io -u "$GITHUB_REPOSITORY_OWNER" \
            --password-stdin <<< "$TOKEN"

      - name: Docker Login to DockerHub
        if: needs.determine_registries.outputs.dockerhub == 'true'
        uses: docker/login-action@v3.3.0
        with:
          username: ${{ secrets.DOCKERHUB_USER }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3.9.0

      - name: Docker Build & Push
        uses: docker/build-push-action@v6.13.0
        with:
          context: ${{ inputs.context }}
          file: ${{ inputs.context }}/Dockerfile
          tags: ${{ env.REPO_TAGS }}
          push: true
